qui{
// Standardize the names
replace chinesename = "台新国际商业银行香港分行" if chinesename == "台新国际商业银行股份有限公司香港分行"
replace englishname = "Taishin International Bank Hong Kong Branch" if englishname == "Taishin International Bank Co., Ltd Hong Kong Branch"
replace chinesename = "新加坡联盟投资管理有限公司" if chinesename == "新盟投资管理公司"
replace englishname = "Singapore Consortium Investment Management Limited" if englishname == "Singapore Consortium Investment Management Limited"
replace chinesename = "南方东英资产管理有限公司" if chinesename == "南方东英资产管理私人有限公司"
replace englishname = "CSOP Asset Management Limited" if englishname == "CSOP ASSET MANAGEMENT PTE LTD"
replace chinesename = "贝莱德基金顾问" if chinesename == "贝莱德基金顾问公司"
replace englishname = "BlackRock Fund Advisors" if englishname == "BlackRock Fund Advisors"
replace chinesename = "Henderson Global Investors Limited" if chinesename == "瀚森全球投资有限公司"
replace englishname = "Henderson Global Investors Limited" if englishname == "Henderson Global Investors Limited"
replace chinesename = "太平洋投资管理亚洲私营有限公司" if chinesename == "太平洋投资管理公司亚洲私营有限公司"
replace englishname = "PIMCO Asia Pte Limited" if englishname == "PIMCO Asia Pte Ltd"
replace chinesename = "中国工商银行伦敦分行" if chinesename == "中国工商银行（伦敦）有限公司"
replace englishname = "Industrial and Commercial Bank of China Limited London Branch" if englishname == "ICBC (London) PLC"
replace chinesename = "纽伯格伯曼欧洲有限公司" if chinesename == "路博迈欧洲有限公司"
replace chinesename = "韩国投资公司" if chinesename == "韩国投资公社"
replace chinesename = "丰收投资管理（香港）有限公司" if chinesename == "弘收投资管理（香港）有限公司"
replace chinesename = "KEB 韩亚银行" if chinesename == "株式会社韩亚银行"
replace englishname = "KEB Hana Bank" if englishname == "Keb Hana Bank"
replace chinesename = "盘古银行资产管理有限公司" if chinesename == "盘谷资产管理有限公司"
replace englishname = "BBL Asset Management Company Limited" if englishname == "BBL Asset Management Co.,LTD"
replace chinesename = "Emso Asset Management Limited" if chinesename == "安索资产管理有限公司"
replace englishname = "Emso Asset Management Limited" if englishname == "Emso Asset Management Limited"
replace chinesename = "Mackenzie Financial Corporation" if chinesename == "迈凯希金融公司"
replace chinesename = "德商德意志银行股份有限公司台北分行" if chinesename == "德意志银行股份有限公司台北分行"
replace chinesename = "交通银行（香港）有限公司" if chinesename == "交通银行股份有限公司香港分行"
replace englishname = "Bank of Communications (Hong Kong) Limited" if englishname == "Bank of Communications Co., Ltd. Hong Kong Branch"
replace chinesename = "加拿大丰业亚洲有限公司" if chinesename == "加拿大丰业银行亚洲有限公司"
replace englishname = "BBNS Asia Limited" if englishname == "The Bank of Nova Scotia Asia Limted"
replace chinesename = "Kuwait Investment Office" if chinesename == "科威特投资办公室"
replace chinesename = "花旗银行香港分行" if chinesename == "花旗银行香港银行"
replace chinesename = "未来资产基金管理有限公司" if chinesename =="Mirae Asset Global Investments Co.,Ltd"
replace chinesename = "未来资产基金管理有限公司" if chinesename =="Mirae Asset Global Investments Co., Ltd"
replace chinesename = "未来资产基金管理有限公司" if chinesename =="未来资产环球投资有限公司"
replace englishname = "Mirae Asset Global Investments Co., Ltd" if englishname =="Mirae Asset Global Investments Co.,Ltd"
replace englishname = "Mirae Asset Global Investments Co., Ltd" if englishname =="Mirae Asset Global Investments Co., Ltd."
replace chinesename = "Vanguard Investments Australia Ltd" if chinesename == "领航投资澳洲有限公司"
replace englishname = "Vanguard Investments Australia Ltd" if englishname =="Vanguard Investment Australia Ltd"
replace chinesename = "台新国际商业银行股份有限公司" if chinesename == "台新国际商业银行国际金融业务分行"
replace englishname = "Taishin International Bank Co., Ltd." if englishname =="Taishin International Bank (Overseas Business Unit)"
replace chinesename = "Eaton Vance Management" if chinesename == "伊顿万斯管理"
replace chinesename = "星展银行" if chinesename == "星展银行有限公司"
replace englishname = "DBS Bank Ltd" if englishname =="Dbs Bank Limited"
replace chinesename = "中国银行股份有限公司香港分行" if chinesename == "中国银行（香港）有限公司"
replace englishname = "Bank of China Limited Hong Kong Branch" if englishname =="Bank of China (Hong Kong) Limited"
replace chinesename = "AllianceBernstein Hong Kong Limited" if chinesename == "联博香港有限公司"
replace chinesename = "开泰银行资产管理有限公司" if chinesename == "开泰基金管理有限公司"
replace englishname = "Kasikorn Asset Management Company Limited" if englishname =="Kasikorn Asset Management Co.,Ltd"
replace chinesename = "韩国央行" if chinesename == "韩国银行"
replace chinesename = "韩国投资证券有限公司" if chinesename == "韩国投资证券株式会社"
replace chinesename = "永隆银行有限公司" if chinesename == "招商永隆银行有限公司"
replace englishname = "Wing Lung Bank Limited" if englishname =="CMB Wing Lung Bank Limited"
replace chinesename = "第一商业银行股份有限公司" if chinesename == "第一商业银行股份有限公司国际金融业务分行"
replace englishname = "First Commercial Bank, Ltd." if englishname =="First Commercial Bank Offshore Banking Branch"
replace chinesename = "宏利投资管理（香港）有限公司" if chinesename == "宏利资产管理（香港）有限公司"
replace englishname = "Manulife Investment Management (Hong Kong) Limited" if englishname =="Manulife Asset Management (Hong Kong) Limited"
replace chinesename = "Manulife Investment Management (US) LLC" if chinesename == "Manulife Asset Management (US) LLC"
replace englishname = "Manulife Investment Management (US) LLC" if englishname == "Manulife Asset Management (US) LLC"
replace chinesename = "CI Investments Inc" if chinesename == "CI投资管理公司"
replace englishname = "CI Investments Inc" if englishname =="CI Investments Inc."
replace chinesename = "HSBC Global Asset Management (UK) Limited" if chinesename == "汇丰环球资产管理（英国）有限公司"
replace chinesename = "UBS Asset Management (Australia) Ltd" if chinesename == "瑞银资产管理（澳大利亚）股份公司"
replace chinesename = "OFI Asset Management" if chinesename == "法国欧菲资产管理公司"
replace chinesename = "KBC Asset Management NV" if chinesename == "比利时联合资产管理有限公司"
replace englishname = "KBC Asset Management NV" if englishname =="KBC Asset Management N.V."
replace chinesename = "智慧树资产管理公司" if chinesename == "WisdomTree资产管理"
replace englishname = "WisdomTree Asset Management Inc." if englishname =="WisdomTree Asset Management, Inc."
replace englishname = "WisdomTree Asset Management Inc." if englishname =="WisdomTree Asset Management lnc."
replace chinesename = "Morgan Stanley Investment Management Inc" if chinesename == "摩根士丹利投资管理公司"
replace englishname = "Morgan Stanley Investment Management Inc" if englishname =="Morgan Stanley Investment Management Inc."
replace chinesename = "Boston Management and Research" if chinesename == "波士顿管理与研究"
replace chinesename = "The Vanguard Group Inc." if chinesename == "领航集团有限公司"
replace englishname = "The Vanguard Group Inc." if englishname =="The Vanguard Group, Inc."
replace chinesename = "道明资产管理有限公司" if chinesename == "道明资产管理公司"
replace chinesename = "Davidson Kempner Capital Management LP" if chinesename == "德骥资本管理公司"
replace chinesename = "Ontario Teachers' Pension Plan Board" if chinesename == "安大略省教师养老金计划委员会"
replace englishname = "Ontario Teachers' Pension Plan Board" if englishname =="Ontario Teachers' Pension  Plan Board"
replace chinesename = "Van Eck Associates Corporation" if chinesename == "泛达公司"
replace chinesename = "中信证券国际投资管理（香港）有限公司" if chinesename == "中信里昂资产管理有限公司"
replace englishname = "CITIC Securities International Investment Management (HK) Limited" if englishname == "CLSA Asset Management Ltd."
replace chinesename = "Aspen Hill Partners (Hong Kong) Limited" if chinesename == "Aspen Hill Partners (Hong Kong) Ltd"
replace englishname = "Aspen Hill Partners (Hong Kong) Limited" if englishname == "Aspen Hill Partners (Hong Kong) Ltd"
replace chinesename = "Avanda Investment Management Pte. Ltd" if chinesename == "Avanda投资管理私人有限公司"
replace englishname = "Avanda Investment Management Pte. Ltd" if englishname == "Avanda Investment Management Pte. Ltd."
replace chinesename = "BFAM Partners (Hong Kong) Limited" if chinesename =="BFAM合伙（香港）有限公司"
replace chinesename = "DNCA Finance" if chinesename =="DNCA金融"
replace englishname = "DNCA Finance" if englishname =="DNCA FINANCE"
replace chinesename = "Exchange Traded Concepts, LLC" if chinesename =="Exchange Traded Concepts LLC"
replace englishname = "Exchange Traded Concepts LLC" if englishname =="Exchange Traded Concepts, LLC"
replace chinesename = "GAM国际管理有限公司" if chinesename =="GAM International Management Limited"
replace chinesename = "GMO有限责任公司" if chinesename =="Grantham Mayo Van Otterloo Co. LLC"
replace englishname = "Grantham, Mayo, Van Otterloo & Co.LLC" if englishname =="Grantham Mayo Van Otterloo Co. LLC"
replace chinesename = "J.P.Morgan Investment Management Inc." if chinesename =="J.P. Morgan Investment Management Inc."
replace englishname = "J.P.Morgan Investment Management Inc." if englishname =="J.P. Morgan Investment Management Inc."
replace chinesename = "J.P.Morgan Securities Asia Private Limited" if chinesename =="J.P. Morgan Securities Asia Private Limited"
replace englishname = "J.P.Morgan Securities Asia Private Limited" if englishname =="J.P. Morgan Securities Asia Private Limited"
replace chinesename = "KB资产运用" if chinesename =="KB资产运用有限公司"
replace englishname = "KB Asset Management  Co., Ltd" if englishname =="KB Asset Management Co., Ltd."
replace chinesename = "L&R资本有限公司" if chinesename =="L and R Capital Limited"
replace chinesename = "L&R资本有限公司" if chinesename =="析理资本有限公司"
replace englishname = "L&R Capital Limited" if englishname =="L and R Capital Limited"
replace chinesename = "Lord Abbett and Co. LLC" if chinesename =="Lord Abbett and Co.LLC"
replace englishname = "Lord Abbett and Co.LLC" if englishname =="Lord Abbett and Co. LLC"
replace chinesename = "未来资产基金管理有限公司" if chinesename =="Mirae Asset Global Investments Co.,Ltd"
replace chinesename = "未来资产基金管理有限公司" if chinesename =="未来资产基金管理公司"
replace englishname = "Mirae Asset Global Investments Co., Ltd" if englishname =="Mirae Asset Global Investments Co.,Ltd"
replace englishname = "Mirae Asset Global Investments Co., Ltd" if englishname =="Mirae Asset Global Investments Co., Ltd."
replace chinesename = "NH Investment and Securities Co. Ltd" if chinesename =="NH Investment and Securities Co.Ltd"
replace englishname = "NH Investment and Securities Co. Ltd" if englishname =="NH Investment and Securities Co.Ltd"
replace chinesename = "Nordea Investment Management AB" if chinesename =="Nordea投资管理公司"
replace chinesename = "PGGM Asset Management" if chinesename =="PGGM资产管理有限公司"
replace englishname = "PGGM Asset Management" if englishname =="PGGM Asset Management B.V."
replace chinesename = "QIC Private Capital Pty Limited" if chinesename =="QIC Private Capital Pty Ltd"
replace englishname = "QIC Private Capital Pty Limited" if englishname =="QIC Private Capital Pty Ltd"
replace chinesename = "UBP Asset Management (Europe) S.A." if chinesename =="UBP Asset Management(Europe)S.A."
replace englishname = "UBP Asset Management (Europe) S.A." if englishname =="UBP Asset Management(Europe)S.A."
replace chinesename = "Vanguard Global Advisers LLC" if chinesename =="Vanguard Global Advisers, LLC"
replace englishname = "Vanguard Global Advisers LLC" if englishname =="Vanguard Global Advisers, LLC"
replace chinesename = "三井住友德思资产管理股份有限公司" if chinesename =="三井住友德思资产管理株式会社"
replace englishname = "Sumitomo Mitsui DS Asset Management Company Limited" if englishname =="Sumitomo Mitsui DS Asset Management Company, Limited"
replace chinesename = "三井住友银行" if chinesename =="三井住友银行株式会社"
replace chinesename = "三井住友银行" if chinesename =="三井住友银行股份有限公司"
replace chinesename = "三菱日联国际资产管理有限公司" if chinesename =="三菱日联国际资产管理公司"
replace chinesename = "三菱日联银行" if chinesename =="三菱日联银行股份有限公司"
replace englishname = "MUFG Bank, Ltd." if englishname =="MUFG Bank Ltd"
replace chinesename = "东兴证券（香港）资产管理有限公司" if chinesename =="东兴证券（香港）资产管理公司"
replace englishname = "Dongxing Securities (Hong Kong) Asset Management Company Limited" if englishname =="Dongxing Securities(HongKong)Asset Management Company Limited"
replace chinesename = "东方汇理资产管理（卢森堡）公司" if chinesename =="东方汇理卢森堡资产管理公司"
replace chinesename = "东方汇理资产管理公司" if chinesename =="东方汇理资产管理"
replace chinesename = "中国光大银行股份有限公司(香港分行)" if chinesename =="中国光大银行股份有限公司香港分行"
replace englishname = "China Everbright Bank Company Limited (Hong Kong Branch)" if englishname =="China Everbright Bank Co., Ltd Hong Kong Branch"
replace chinesename = "元大证券（香港）有限公司" if chinesename =="元大宝来证券（香港）有限公司"
replace chinesename = "元大证券信托股份有限公司" if chinesename =="元大证券投资信托股份有限公司"
replace englishname = "Yuanta Securities Investment Trust Co.,Ltd" if englishname =="Yuanta Securities Investment Trust Co., Ltd."
replace chinesename = "兴国资产管理" if chinesename =="兴国资产管理公司"
replace chinesename = "冈三资产管理有限公司" if chinesename =="冈三资产管理股份有限公司"
replace englishname = "Okasan Asset Management Co., Ltd" if englishname =="Okasan Asset Management Co.,Ltd"
replace chinesename = "华侨永亨银行有限公司" if chinesename =="华侨永亨银行股份有限公司"
replace englishname = "OCBC Wing Hang Bank Limited" if englishname =="OCBC Wing Hang Bank Limited（Macau）"
replace chinesename = "华侨永亨银行香港分行" if chinesename =="华侨银行（香港分行）"
replace englishname = "Overseas Chinese Banking Corporation HK Branch" if englishname =="Oversea-Chinese Banking Corporation Limited (Hong Kong Branch)"
replace chinesename = "发逻全球咨询有限公司" if chinesename =="发逻资产管理公司"
replace englishname = "Pharo Global Advisors Limited" if englishname =="Phrao Global Advisors Limited"
replace chinesename = "国泰世华商业银行股份有限公司香港分行" if chinesename =="国泰世华商业银行股份有限公司-香港分行"
replace englishname = "Cathay United Bank Company Limited Hong Kong Branch" if englishname =="Cathay United Bank Company, Limited-Hong Kong Branch"
replace chinesename = "壳牌资产管理有限公司" if chinesename =="壳牌资产管理公司"
replace chinesename = "大华银行有限公司" if chinesename =="大华银行有限公司-QFII"
replace englishname = "United  Overseas Bank Limited" if englishname =="United Overseas Bank Limited-QFII"
replace chinesename = "大和资产管理株式会社" if chinesename =="大和证券投资信托委托株式会社"
replace englishname = "Daiwa Asset Management Co. Ltd." if englishname =="Daiwa Asset Management Co. Ltd."
replace chinesename = "威灵顿投资管理国际有限公司" if chinesename =="威灵顿管理国际有限公司"
replace englishname = "Wellington Management International Limited" if englishname =="Wellington Management International Ltd"
replace chinesename = "安盛基金管理有限公司" if chinesename =="安盛环球基金管理公司"
replace chinesename = "安盛投资管理巴黎公司" if chinesename =="安盛投资管理有限公司（巴黎）"
replace chinesename = "富达管理及研究公司有限责任公司" if chinesename =="富达管理研究有限公司"
replace chinesename = "山金资产管理(香港)有限公司" if chinesename =="山金资产管理（香港）有限公司"
replace chinesename = "Deutsche Bank A.G.Hong Kong Branch" if chinesename =="德意志银行香港分行"
replace chinesename = "Deutsche Bank A.G.Hong Kong Branch" if chinesename =="德意志银行股份有限公司香港分行"
replace chinesename = "Deutsche Bank A.G.Hong Kong Branch" if chinesename =="Deutsche Bank A.G. HongKong Branch"
replace englishname = "Deutsche Bank A.G. Hong Kong Branch" if englishname =="Deutsche Bank AG Hong Kong Branch"
replace englishname = "Deutsche Bank A.G. Hong Kong Branch" if englishname =="Deutsche Bank A.G. HongKong Branch"
replace chinesename = "Deutsche Bank A.G. Singapore Branch" if chinesename =="德意志银行有限公司新加坡分行"
replace chinesename = "Deutsche Bank A.G. Singapore Branch" if chinesename =="Deutsche Bank AG Singapore Branch"
replace chinesename = "惠理基金管理香港有限公司" if chinesename =="惠理基金香港管理有限公司"
replace chinesename = "招商资产管理（香港）有限公司" if chinesename =="招商资产（香港）有限公司"
replace chinesename = "招商银行股份有限公司香港分行" if chinesename =="招商银行香港分行"
replace englishname = "China Merchants Bank Co Ltd, Hong Kong Branch" if englishname =="China Merchants Bank Hong Kong Branch"
replace chinesename = "新韩金融投资公司" if chinesename =="新韩金融投资"
replace chinesename = "方圆投资管理（香港）有限公司" if chinesename =="方圆基金管理（香港）有限公司"
replace chinesename = "星展银行有限公司香港分行" if chinesename =="星展银行（香港）有限公司"
replace englishname = "DBS Bank Ltd., Hong Kong Branch" if englishname =="Dbs Bank (HK) Limited"
replace chinesename = "柏瑞投资爱尔兰有限公司" if chinesename =="柏瑞投资（爱尔兰）有限公司"
replace chinesename = "法国巴黎资产管理" if chinesename =="法国巴黎投资管理"
replace chinesename = "渣打银行(香港)有限公司" if chinesename =="渣打银行（香港）有限公司"
replace chinesename = "瑞士再保险亚洲私人有限公司" if chinesename =="瑞士再保险私人有限公司"
replace englishname = "Swiss Re Asia Pte. Ltd." if englishname =="Swiss RE Asia PTE. LTD."
replace chinesename = "瑞士嘉盛银行有限公司" if chinesename =="瑞士嘉盛银行"
replace englishname = "Bank J. Safra Sarasin Ltd" if englishname =="Bank J.Safra Sarasin Ltd"
replace chinesename = "贝莱德顾问(英国)有限公司" if chinesename =="贝莱德顾问（英国）有限公司"
replace chinesename = "雅伦资本私人有限公司" if chinesename =="雅鲁资本私人有限公司"
replace chinesename = "香港金融管理局" if chinesename =="香港金管局"
replace chinesename = "老挝中央银行" if chinesename =="Bank of Lao P.D.R"
replace chinesename = "Bank of Lao P.D.R" if chinesename =="Bank of Lao P.D.R"
replace chinesename = "Labour Market Supplementary Pension Scheme" if chinesename =="Arbejdsmarkedets Tillaegspension (ATP)"
replace englishname = "Labour Market Supplementary Pension Scheme" if englishname =="Arbejdsmarkedets Tillaegspension (ATP)"
replace chinesename = "AllianceBernstein L.P." if chinesename =="联博有限合伙"
replace englishname = "AllianceBernstein L.P." if englishname =="AllianceBernstein L.P."
replace chinesename = "中国建设银行股份有限公司伦敦分行" if chinesename =="中国建设银行（伦敦）有限公司"
replace englishname = "China Construction Bank London branch" if englishname =="China Construction Bank（London) Limited"
replace chinesename = "中国工商银行新加坡分行" if chinesename =="中国工商银行股份有限公司新加坡分行"
replace englishname = "Industrial and Commercial Bank of China Singapore Branch" if englishname =="Industrial and Commercial Bank of China Limited, Singapore Branch"
replace chinesename = "CICC Financial Products Ltd." if chinesename =="中金金融产品有限公司"
replace englishname = "CICC Financial Products Ltd." if englishname =="CICC Financial Products Ltd"
replace chinesename = "Macquarie Bank Limited Singapore Branch" if chinesename =="麦格理银行有限公司新加坡分公司"
replace englishname = "Macquarie Bank Limited Singapore Branch" if englishname =="Macquarie Bank Limited Singapore Branch"
replace chinesename = "Baillie Gifford and Co Limited" if chinesename =="柏基公司"
replace englishname = "Baillie Gifford and Co Limited" if englishname =="Baillie Gifford & Co"
replace chinesename = "澳新银行集团有限公司香港分行" if chinesename =="澳盛银行集团有限公司香港分行"
replace englishname = "Australia and New Zealand Banking Group Limited,Hong Kong Branch" if englishname =="Australia and New Zealand Banking Group Limited, Hong Kong Branch"
replace chinesename = "Lombard Odier Asset Management (Europe) Limited" if chinesename =="隆奥资产管理（欧洲）有限公司"
replace englishname = "Lombard Odier Asset Management (Europe) Limited" if englishname =="Lombard Odier Asset Management(Europe)Limited"
replace chinesename = "富邦人寿保险股份有限公司" if chinesename =="富邦产物保险股份有限公司"
replace englishname = "Fubon Life Insurance Co., Ltd" if englishname =="Fubon Insurance Company Limited"
replace chinesename = "Qube Research and Technologies Limited" if chinesename =="立方科研资产管理有限公司"
replace englishname = "Qube Research and Technologies Limited" if englishname =="Qube Research and Technologies Limited"
replace chinesename = "Key Square Capital Management LLC" if chinesename =="基斯克威尔资产管理公司"
replace englishname = "Key Square Capital Management LLC" if englishname =="Key Square Capital Management LLC"
replace chinesename = "State Street Global Advisors Limited" if chinesename =="道富环球投资有限公司"
replace chinesename = "Nexus Investment Advisors Limited" if chinesename =="裕丰资产管理有限公司"
replace chinesename = "Credit Industriel et Commercial Singapore Branch" if chinesename =="法国工商信贷银行新加坡分行"
replace chinesename = "华侨永亨银行香港分行" if chinesename =="华侨银行有限公司香港分行"
replace englishname = "Overseas Chinese Banking Corporation HK Branch" if englishname =="Oversea-Chinese Banking Corporation Limited, Hong Kong Branch"
replace chinesename = "中国信托商业银行股份有限公司香港分行" if chinesename =="中国信托商业银行股份有限公司国际金融业务分行"
replace englishname = "CTBC Bank Co., Ltd., Hong Kong Branch" if englishname =="CTBC Bank Co.,LTD.,Offshore Banking Unit"
replace chinesename = "中国建设银行股份有限公司新西兰分行" if chinesename =="中国建设银行（新西兰）有限公司"
replace englishname = "China Construction Bank Corporation New Zealand Branch" if englishname =="China Construction Bank (New Zealand) Limited"
replace chinesename = "DWS Investment GmbH" if chinesename =="德意志资产及财富管理投资有限公司"
replace englishname = "DWS Investment GmbH" if englishname =="Deutsche Asset & Wealth Management Investment GmbH"
replace chinesename = "纽伯格伯曼新加坡" if chinesename =="路伯迈新加坡有限公司"
replace chinesename = "纽伯格伯曼新加坡" if chinesename =="路博迈新加坡有限公司"
replace englishname = "Neuberger Berman Singapore Pte.Limited" if englishname =="Neuberger Berman Singapore Pte. Limited"
replace chinesename = "捷克国家银行" if chinesename =="Czech National Bank"
replace chinesename = "富舜资产管理（香港）有限公司" if chinesename =="富舜投资管理（香港）有限公司"
replace englishname = "Total Invest Group Asset Management (Hong Kong) Limited" if englishname =="Total Invest Group Asset Management (Hong Kong) Limited"
replace chinesename = "利安资金管理有限公司" if chinesename =="利安资金管理公司"
replace chinesename = "利安资金管理有限公司" if chinesename =="Lion Global Investors Limited"
replace englishname = "Lion Global Investors Limited" if englishname =="Lion GlobalInvestors Limited"
replace chinesename = "永丰商业银行股份有限公司（香港分行）" if chinesename =="永丰商业银行股份有限公司香港分行"
replace englishname = "Bank SinoPac Hong Kong Branch" if englishname =="Bnak Sinopac Hong Kong Branch"
replace chinesename = "中国建设银行东京分行" if chinesename =="中国建设银行股份有限公司东京分行"
replace englishname = "China Construction Bank Tokyo branch" if englishname =="China Construction Bank Corporation Tokyo Branch"
replace chinesename = "中国工商银行（澳门）股份有限公司" if chinesename =="中国工商银行股份有限公司澳门分行"
replace englishname = "Industrial and Commercial Bank of China (Macau) Limited" if englishname =="The Industrial and Commercial Bank of China Macau Branch"
replace chinesename = "交通银行台北分行" if chinesename =="交通银行股份有限公司台北分行"
replace englishname = "Bayern Invest Investment Management Company Limited" if englishname =="BayernInvest Investment Management Company Limited"
replace englishname = "BlackRock (Luxembourg) S.A." if englishname =="BlankRock (Luxembourg) S.A."
drop if chinesename =="Chinese name"
drop if chinesename == "境外机构中文全称"
}